### ISSUE TITLE
No dock items added if 'erase_all' is true

### ISSUE THREAD

**Issue by acgourley** [wayofdev/ansible-role-dock#9]
this config results in an empty dock

```
dockutil:
  erase_all: true
  install: true
  tap: lotyp/formulae/dockutil # By default 3.x tap is used
  dockitems:
    - label: Chrome
      action: add
      path: /Applications/Google Chrome.app
      position: 1
    - label: Sublime Text
      action: add
      path: /Applications/Sublime Text.app
      position: 2
      
```

Seen on OSX Monterey via config over SSH.

Task output

```
TASK [lotyp.dock : Dockutil | Filter out already added items] ****************************************************************************************************************************************************************************************************************************************************************************************
ok: [at-m1ni-04.local] => (item={'changed': False, 'stdout': 'Chrome was not found in /Users/content/Library/Preferences/com.apple.dock.plist', 'stderr': 'Find failed for Chrome in /Users/content/Library/Preferences/com.apple.dock.plist', 'rc': 1, 'cmd': "dockutil -f 'Chrome'", 'start': '2022-06-13 22:46:48.562331', 'end': '2022-06-13 22:46:48.572103', 'delta': '0:00:00.009772', 'failed': False, 'msg': 'non-zero return code', 'invocation': {'module_args': {'_raw_params': "dockutil -f 'Chrome'", '_uses_shell': True, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}, 'stdout_lines': ['Chrome was not found in /Users/content/Library/Preferences/com.apple.dock.plist'], 'stderr_lines': ['Find failed for Chrome in /Users/content/Library/Preferences/com.apple.dock.plist'], 'failed_when_result': False, 'item': {'label': 'Chrome', 'action': 'add', 'path': '/Applications/Google Chrome.app', 'position': 1}, 'ansible_loop_var': 'item'})
ok: [at-m1ni-04.local] => (item={'changed': False, 'stdout': 'Sublime Text was not found in /Users/content/Library/Preferences/com.apple.dock.plist', 'stderr': 'Find failed for Sublime Text in /Users/content/Library/Preferences/com.apple.dock.plist', 'rc': 1, 'cmd': "dockutil -f 'Sublime Text'", 'start': '2022-06-13 22:46:48.843058', 'end': '2022-06-13 22:46:48.852745', 'delta': '0:00:00.009687', 'failed': False, 'msg': 'non-zero return code', 'invocation': {'module_args': {'_raw_params': "dockutil -f 'Sublime Text'", '_uses_shell': True, 'warn': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}, 'stdout_lines': ['Sublime Text was not found in /Users/content/Library/Preferences/com.apple.dock.plist'], 'stderr_lines': ['Find failed for Sublime Text in /Users/content/Library/Preferences/com.apple.dock.plist'], 'failed_when_result': False, 'item': {'label': 'Sublime Text', 'action': 'add', 'path': '/Applications/Sublime Text.app', 'position': 2}, 'ansible_loop_var': 'item'})
```
